name: go_app_v2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  url_launcher: ^6.1.5
  # google_mobile_ads: ^2.0.1
  google_mobile_ads: ^2.0.1
  video_player: ^2.4.7
  mailto: ^2.0.0
  shared_preferences: ^2.0.15
  # wallpaper_manager: ^1.0.10
  path_provider: ^2.0.11
  gallery_saver: ^2.3.2
  carousel_slider: ^4.1.1
  share_plus: ^4.1.0
  flutter_share: ^2.0.0
  wallpaper_manager_flutter: ^0.0.2
  audioplayers: ^0.19.0
  zoom_tap_animation: ^1.1.0
  flutter_bounce: ^1.1.0
  gif: ^2.1.2
  # social_image_share: ^0.0.2
  # flutter_cache_manager: ^3.1.2
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  fast_i18n: ^5.12.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/splash_screen/
    - assets/Sonidos/
    - assets/dummy/
    - assets/dummy/dummy_wallpaper.jpg
    - assets/Ref2/PERDISTE.mp4
    - assets/Ref2/GANASTE.mp4
    - assets/QuizList.json
    - assets/Ref2/
    - assets/Ref1/
    - assets/Ref1/Slider/Apple.png
    - assets/OtherApps.json
    - assets/Ref1/Slider/Alexby.png
    - assets/Ref1/Slider/Anuel.png
    - assets/Ref1/Slider/Auronplay.png
    - assets/Ref1/Slider/Billie.png
    - assets/Ref1/Slider/Bizarrap.png
    - assets/Ref1/Slider/Bunny.png
    - assets/Ref1/Slider/Camilo.png
    - assets/Ref1/Slider/Christiano Ronaldo.png
    - assets/Ref1/Slider/Coscu.png
    - assets/Ref1/Slider/Cro.png
    - assets/Ref1/Slider/Doom.png
    - assets/Ref1/Slider/Estik.png
    - assets/Ref1/Slider/Fernafloo.png
    - assets/Ref1/Slider/Fontnite.png
    - assets/Ref1/Slider/Frankaster.png
    - assets/Ref1/Slider/Gta5.png
    - assets/Ref1/Slider/Harry.png
    - assets/Ref1/Slider/Ibai.png
    - assets/Ref1/Slider/Jenifer Lopez.png
    - assets/Ref1/Slider/Justin.png
    - assets/Ref1/Slider/Lol.png
    - assets/Ref1/Slider/Luis Suarez.png
    - assets/Ref1/Slider/Luisito.png
    - assets/Ref1/Slider/Magel.png
    - assets/Ref1/Slider/Maluma.png
    - assets/Ref1/Slider/Marvel.png
    - assets/Ref1/Slider/Mesi.png
    - assets/Ref1/Slider/Minecraft.png
    - assets/Ref1/Slider/Momo.png
    - assets/Ref1/Slider/Neymar.png
    - assets/Ref1/Slider/Peke.png
    - assets/Ref1/Slider/Pew di pie.png
    - assets/Ref1/Slider/Rubiuis.png
    - assets/Ref1/Slider/Taylor Swift.png
    - assets/Ref1/Slider/Travi.png
    - assets/Ref1/Slider/Trueno.png
    - assets/Ref1/Slider/Vegetta 777.png
    - assets/Ref1/Slider/Willy Rex.png
    - assets/Ref1/Slider/Wismichu.png
    - assets/Ref1/Slider/Wos.png
    - assets/Ref1/Apps/Apple.png
    - assets/Ref1/Apps/Alexby.png
    - assets/Ref1/Apps/Anuel.png
    - assets/Ref1/Apps/Auronplay.png
    - assets/Ref1/Apps/Billie.png
    - assets/Ref1/Apps/Bizarrap.png
    - assets/Ref1/Apps/Bunny.png
    - assets/Ref1/Apps/Camilo.png
    - assets/Ref1/Apps/Christiano Ronaldo.png
    - assets/Ref1/Apps/Coscu.png
    - assets/Ref1/Apps/Cro.png
    - assets/Ref1/Apps/Doom.png
    - assets/Ref1/Apps/Estik.png
    - assets/Ref1/Apps/Fernafloo.png
    - assets/Ref1/Apps/Fontnite.png
    - assets/Ref1/Apps/Frankaster.png
    - assets/Ref1/Apps/Gta5.png
    - assets/Ref1/Apps/Harry.png
    - assets/Ref1/Apps/Ibai.png
    - assets/Ref1/Apps/Jenifer Lopez.png
    - assets/Ref1/Apps/Justin.png
    - assets/Ref1/Apps/Lol.png
    - assets/Ref1/Apps/Luis Suarez.png
    - assets/Ref1/Apps/Luisito.png
    - assets/Ref1/Apps/Magel.png
    - assets/Ref1/Apps/Maluma.png
    - assets/Ref1/Apps/Marvel.png
    - assets/Ref1/Apps/Mesi.png
    - assets/Ref1/Apps/Minecraft.png
    - assets/Ref1/Apps/Momo.png
    - assets/Ref1/Apps/Neymar.png
    - assets/Ref1/Apps/Peke.png
    - assets/Ref1/Apps/Pew di pie.png
    - assets/Ref1/Apps/Rubiuis.png
    - assets/Ref1/Apps/Taylor Swift.png
    - assets/Ref1/Apps/Travi.png
    - assets/Ref1/Apps/Trueno.png
    - assets/Ref1/Apps/Vegetta 777.png
    - assets/Ref1/Apps/Willy Rex.png
    - assets/Ref1/Apps/Wismichu.png
    - assets/Ref1/Apps/Wos.png
    - assets/Ref1/intro_juego.mp4
    - assets/Ref3/Todas Nuestras App.png
    - assets/Ref3/Barra de Busqueda.png
    - assets/Ref3/Pop Up Slider Boton.png
    - assets/Ref3/Aleatorio.png
    - assets/Ref3/Barra de Envio.png
    - assets/Ref3/Boton Enviar.png
    - assets/Ref3/fondo aleatorio.png
    - assets/Wallpaper/ic_download.png
    - assets/Wallpaper/ic_set_wallpaper.png
    - assets/Wallpaper/slide_wallpaper.gif
    - assets/Ref2/correct.mp3
    - assets/Ref2/incorrect.mp3

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
